all:
	
	clear
	gcc -o Processos/P1 Processos/P1.c
	gcc -o Processos/P2 Processos/P2.c
	gcc -o Processos/P3 Processos/P3.c
	gcc -o Processos/P4 Processos/P4.c
	gcc -o Processos/P5 Processos/P5.c
	gcc -o Processos/P6 Processos/P6.c
	gcc -o Processos/P7 Processos/P7.c
	gcc -o Processos/P8 Processos/P8.c
	gcc -o Processos/P9 Processos/P9.c
	gcc -o Processos/P10 Processos/P10.c
	
	gcc -Wall -g -o interpretador interpretador.c queue.c
	gcc -Wall -g -o escalonador queue.c escalonador.c 
	./interpretador